spring:
    application:
        name: word-backend

app:
    datasource:
        main:
            driver-class-name: org.postgresql.Driver
            jdbc-url: ${ENV_DB_URL}
            password: ${ENV_DB_PASSWORD}
            username: ${ENV_DB_USERNAME}


server:
    error:
        include-binding-errors: always
        include-message: always

