app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/word-backend
      password: 'password'
      username: emyr.williams
      pool-size: 30