app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/word-backend
      password: 'password'
      username: emyr.williams
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8081

spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: emyr.williams
    password: 'password'
    url: jdbc:postgresql://localhost:5432/word-backend
    mixed: true
    driver-class-name: org.postgresql.Driver