spring:
    application:
        name: word-backend
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration
        user: ${ENV_DB_USERNAME}
        password: ${ENV_DB_PASSWORD}
        url: ${ENV_DB_URL}
        mixed: true
        driver-class-name: org.postgresql.Driver


app:
    datasource:
        main:
            driver-class-name: org.postgresql.Driver
            jdbc-url: ${ENV_DB_URL}
            password: ${ENV_DB_PASSWORD}
            username: ${ENV_DB_USERNAME}


server:
    error:
        include-binding-errors: always
        include-message: always

